app:
  url: "http://localhost:8082/jobexecution"
  frontend:
    url: http://localhost:3000/
    email-confirm-base-url: http://localhost:8082/jobexecution/api/v1/auth/confirm-email
  security:
    jwt:
      secretKey: f969730dbe8beca1989c9182777f097a85512d479240ee5a2357c46838a3d54a
      expiration: 1800000 # 30 min
      refreshToken:
        expiration: 86400000 # 1 day

server:
  port: 8082
  servlet:
    context-path: /jobexecution
spring:
  application:
    name: Jobexecution
  profiles:
    active: Test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

jobexecution:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/jobexecution
    username: Admin   # Add your actual username here
    password:    # Add your actual password here (if any)
    driverClassName: org.postgresql.Driver  # Explicitly define the driver
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 30000  # 30 seconds
    maxLifetime: 30000  # 30 seconds
    poolName: jobexecutionDataSource
    connectionTestQuery: SELECT 1
    leakDetectionThreshold: 5000  # 5 seconds


